### ISSUE TITLE
Integrate QuickBlox with react native

### ISSUE THREAD

**Issue by Asif-chohan** [QuickBlox/quickblox-react-native-sdk#1]
I'm trying to use quickblox with react-native. The user has been successfully created and connected to QB.chat. But when I create a dialog as:

QB.chat
      .createDialog({
        type: QB.chat.DIALOG_TYPE.CHAT,
        name: "new dialog",
        occupantsIds: [99125620]
      })
      .then(function(dialog) {
        console.log(dialog);
        // handle as necessary, i.e.
        // subscribe to chat events, typing events, etc.
      })
      .catch(function(e) {
        console.log( e);
        // handle error
      });

it gives an error:
![Screenshot from 2019-11-01 09-04-13](https://user-images.githubusercontent.com/35171930/68001617-a5dc3480-fc86-11e9-822f-b6582706f750.png)

**Comment by ghost** [comment]
Hello @Asif-chohan 

Thank you for contacting QuickBlox support. 

Have you tried to reproduce the reported behavior on clear QB ReactNative sample? 

Have you tried to create a dialog using QB ReactNative documentation? - https://docs.quickblox.com/docs/react-native-chat#section--create-a-new-dialog-

Does the reported issue reproduce only while the creation of 1-1 chat? Or for group and public chat too? 

Looking forward to your reply.

**Comment by ghost** [comment]
Hello @Asif-chohan 

Unfortunately, I haven't received any feedback from you. 
The status of the ticket changed to "Closed". 

Please, re-open this ticket if the issue is still actual for you.
