### ISSUE TITLE
CocoaPods could not find compatible versions for pod "quickblox-react-native-sdk"

### ISSUE THREAD

**Issue by sagar-chhatrola** [QuickBlox/quickblox-react-native-sdk#15]
Pod install failed.

`[!] CocoaPods could not find compatible versions for pod "quickblox-react-native-sdk":
  In Podfile:
    quickblox-react-native-sdk (from `../node_modules/quickblox-react-native-sdk`)

Specs satisfying the `quickblox-react-native-sdk (from `../node_modules/quickblox-react-native-sdk`)` dependency were found, but they required a higher minimum deployment `target.``

**Comment by midoalone** [comment]
Just edit the Podfile and change the platform version to be 10.0

`platform :ios, '10.0'`

**Comment by stephanoparaskeva** [comment]
Hey please join a Community made QuickBlox Slack so we can help each other on the QB platform:

https://join.slack.com/t/quickbloxcommunity/shared_invite/zt-q0s3bx3b-YzacqhEfPeBGbEdgEtFr1g

**Comment by dodeja27** [comment]
I'm also facing the same issue

**Comment by mandhu** [comment]
platform :ios, '12.0'

**Comment by ghost** [comment]
Hello,

This is Nikolay from QuickBlox support.

Please make sure that you followed these instructions on how to install the QuickBlox React Native SDK:
[https://docs.quickblox.com/docs/react-native-quick-start](https://docs.quickblox.com/docs/react-native-quick-start)

Also, please make sure that the iOS version in your project’s Podfile is not lower than 13.0 when installing SDK.

Additionally, please check if the string where the iOS deployment target is defined is not commented.
