### ISSUE TITLE
how to delete a qb user in rn quicklbox

### ISSUE THREAD

**Issue by proswe** [QuickBlox/quickblox-react-native-sdk#16]

**Comment by stephanoparaskeva** [comment]
Hey please join a Community made QuickBlox Slack so we can help each other on the QB platform:

https://join.slack.com/t/quickbloxcommunity/shared_invite/zt-q0s3bx3b-YzacqhEfPeBGbEdgEtFr1g

**Comment by ghost** [comment]
@cloudtenlabs Hello,

This is Nikolay from QuickBlox support.

Unfortunately, this functionality has not been described in our React Native SDK.

You may refer to the iOS and Android documentation to write it natively:
[https://docs.quickblox.com/docs/ios-users#delete-user](https://docs.quickblox.com/docs/ios-users#delete-user)
[https://docs.quickblox.com/docs/android-users#delete-user](https://docs.quickblox.com/docs/android-users#delete-user)
