### ISSUE TITLE
QB.chat.getDialogMessages markAsRead not updating dialogs in Android

### ISSUE THREAD

**Issue by Saumyadip-Pramanik** [QuickBlox/quickblox-react-native-sdk#2]
The query parameter 'markAsRead=true' in QB.chat.getDialogMessages method is supposed to update the unread message count received in QB.chat.getDialogs method. Which is working properly in iOS. However, it is not updating the value in Android. Tested in both emulator and physical device.

React Native Version: 0.61.4

**Comment by ghost** [comment]
Hello @Saumyadip-Pramanik 

Thank you for contacting QuickBlox support.

Have you tried to reproduce the reported behavior on clear QB sample? 

Looking forward to your reply.

**Comment by Saumyadip-Pramanik** [comment]
Hi @QB-vladyslav-vyshniak,
 
Thank you for quick reply, I have not verified the behavior by running the sample but I have gone through the code, as per my understanding from the documentation in official site of QB, the markAsRead key is responsible for marking all messages read, as I am not using the individual message read functionality. So once the above flag is true, getDialogs method should return unread count 0, which is working in ios. My problem is in android, is there any platform-specific flag or implementation deviation ?

**Comment by ghost** [comment]
Hello @Saumyadip-Pramanik 

Take my apologies for the delay in reply. 

The developers have fixed the reported behavior and currently all works as expected with the latest ReactNative SDK version.
Please proceed with the update: https://github.com/QuickBlox/quickblox-react-native-sdk/releases/tag/0.4.11-beta

Let me know if you have any additional questions.
