### ISSUE TITLE
WebRTCView is not cover full space in iOS

### ISSUE THREAD

**Issue by bhoomika-sorathiya** [QuickBlox/quickblox-react-native-sdk#21]
Thanks for providing this awesome package for calling functionality. I am facing issue related to videoView in iPhone. For android, it is covering whole space horizontally. But, for iOS, there is some horizontal space in video view. Please check screenshots attached:

Highlighted space issue with red mark for iOS:

<img width="299" alt="Screenshot 2020-09-02 at 2 29 56 PM" src="https://user-images.githubusercontent.com/61711240/92022738-b5565f00-ed29-11ea-9912-859daa4d3acc.png">

For android, it is working fine highlighted by orange mark:

![Screenshot_2020-09-02-14-39-52-959_com miui gallery](https://user-images.githubusercontent.com/61711240/92023565-f13df400-ed2a-11ea-8466-185c6a4bde68.png)

**Comment by ayushjain1796** [comment]
i am facing the similar issue, has this been solved by someone?

**Comment by ayushjain1796** [comment]
what i have found out, that the video in iphone are of resolution 640x480 and they are not zooming in to fit the aspect ration of the device like android, so if you want to fit the video you can manually change the height to "height*1.2" or other that fits your device screen

**Comment by stephanoparaskeva** [comment]
I am having this problem too, has anyone solved this?
Why is this happening?

**Comment by stephanoparaskeva** [comment]
> what i have found out, that the video in iphone are of resolution 640x480 and they are not zooming in to fit the aspect ration of the device like android, so if you want to fit the video you can manually change the height to "height*1.2" or other that fits your device screen

How do you change resolution/height/width/fps in react native quickblox?

**Comment by stephanoparaskeva** [comment]
Hey please join a Community made QuickBlox Slack so we can help each other on the QB platform:

https://join.slack.com/t/quickbloxcommunity/shared_invite/zt-q0s3bx3b-YzacqhEfPeBGbEdgEtFr1g

**Comment by ghost** [comment]
@stephanoparaskeva @ayushjain1796 @bhoomika-sorathiya 
Hello,

This is Nikolay from QuickBlox support.

Please proceed with the update to the latest stable React Native SDK version - 0.5.14-beta (URL: https://github.com/QuickBlox/quickblox-react-native-sdk/releases/tag/0.5.14-beta) where the reported bug is resolved and the calling functionality works as expected.
