### ISSUE TITLE
QB.chat.markMessageRead - Error: "dialogId" is required.

### ISSUE THREAD

**Issue by marksantoso** [QuickBlox/quickblox-react-native-sdk#22]
Trying to call:

`QB.chat.markMessageRead({messageId: message?.id, dialogId: message?.dialogId})`

and receiving Error: "dialogId" is required.

Can confirm both messageId and dialogId are set in the params, so its unclear why I am receiving this error.

Following instructions from: https://docs.quickblox.com/docs/react-native-chat-advanced

**Comment by marksantoso** [comment]
Documentation is inaccurate. 

Should be:

QB.chat
  .markMessageDelivered({message: { messageId, dialogId }})
  .then(function () { /* marked as "delivered" successfully */ })
  .catch(function (e) { /* handle error */ })

**Comment by stephanoparaskeva** [comment]
Hey please join a Community made QuickBlox Slack so we can help each other on the QB platform:

https://join.slack.com/t/quickbloxcommunity/shared_invite/zt-q0s3bx3b-YzacqhEfPeBGbEdgEtFr1g

**Comment by ghost** [comment]
@marksantoso Hello,

This is Nikolay from QuickBlox support.

Thank you for your feedback.

Please check our updated documentation and let us know if there are any questions:
[https://docs.quickblox.com/docs/react-native-video-calling](https://docs.quickblox.com/docs/react-native-video-calling)
