### ISSUE TITLE
How to upload profile image for user

### ISSUE THREAD

**Issue by AquilSoft** [QuickBlox/quickblox-react-native-sdk#23]
How to upload user profile image in react native sdk

**Comment by stephanoparaskeva** [comment]
Hey please join a Community made QuickBlox Slack so we can help each other on the QB platform:

https://join.slack.com/t/quickbloxcommunity/shared_invite/zt-q0s3bx3b-YzacqhEfPeBGbEdgEtFr1g

**Comment by QB-nikolay-zolotarov** [comment]
@AquilSoft Hello,

This is Nikolay from QuickBlox support.

Please review our documentation and let me know if you have any questions:
[https://docs.quickblox.com/docs/react-native-users#set-user-avatar](https://docs.quickblox.com/docs/react-native-users#set-user-avatar)
