### ISSUE TITLE
how to implement react-native-callkeep

### ISSUE THREAD

**Issue by ayushjain1796** [QuickBlox/quickblox-react-native-sdk#27]
have anyone implemented the react-native-callkeep with the quickblox sdk?

**Comment by stephanoparaskeva** [comment]
Hey please join a Community made QuickBlox Slack so we can help each other on the QB platform:

https://join.slack.com/t/quickbloxcommunity/shared_invite/zt-q0s3bx3b-YzacqhEfPeBGbEdgEtFr1g

**Comment by ghost** [comment]
@ayushjain1796 Hello,

This is Nikolay from QuickBlox support.

Please let me know if the question is still relevant.

**Comment by ghost** [comment]
The issue is being closed as outdated.

If it is still relevant, feel free to open a new issue.
