### ISSUE TITLE
Security Concern - API keys and Secret

### ISSUE THREAD

**Issue by stephanoparaskeva** [QuickBlox/quickblox-react-native-sdk#28]
These keys are stored on the front end. So every client has access to the secret and keys, meaning they can use the API E.g:

```ts 
var CREDENTIALS = {
  appId: 28287,
  authKey: 'XydaWcf8OO9xhGT',
  authSecret: 'JZfqTspCvELAmnW',
  accountKey: 'sdjfnksnlk2bk1k34kb'
};
```

How can one do this and configure without the client ever knowing the AppID,authKey, authSecret or API keys, can we hide some of these keys as this is potentially dangerous?

**Comment by jpgarcia99** [comment]
Have you tried storing them on the backend and fetching them after the user has authenticated with your server?

**Comment by stephanoparaskeva** [comment]
> Have you tried storing them on the backend and fetching them after the user has authenticated with your server?

Great solution, will close this now.
