### ISSUE TITLE
Chat dialog is getting swapped

### ISSUE THREAD

**Issue by Saumyadip-Pramanik** [QuickBlox/quickblox-react-native-sdk#3]
React Native: 0.61.4
QB: quickblox-react-native-sdk/releases/tag/0.4.11-beta

The sender_id and receiver_id in a chat dialog are getting swapped in one to one chat.
The behavior is not consistent but randomly appearing.
Method: ".getDialogMessages"

Please check the attached log for details, here recipient id and sender id are coming the same. which is received on calling ".createDialog"

<img width="1061" alt="Screenshot 2020-01-03 at 20 45 15" src="https://user-images.githubusercontent.com/19325475/71731490-e153d480-2e6a-11ea-9433-60443c131ab0.png">

**Comment by ghost** [comment]
Hello @Saumyadip-Pramanik 

Thank you for contacting QuickBlox support. 

As I have already mentioned in QuickBlox support portal ticket, the developers are investigating the reasons of the reported behavior.
I will let you know as soon as they provide me with any updates.

**Comment by Saumyadip-Pramanik** [comment]
@QB-vladyslav-vyshniak thanks!
You can find the dialogId in above log screenshot.

**Comment by ghost** [comment]
Hello @Saumyadip-Pramanik 

To speed up the investigation process, provide me with the following points:
1. The detailed reproducing steps.
2. The detailed logs (logs should be collected right from the start of application working)
3. Video confirmation.
4. Have you made the request according to QuickBlox ReactNative documentation? - https://docs.quickblox.com/docs/react-native-chat#section-chat-history

I have requested the mentioned points on 10 January via ticket #146282 in QuickBlox support portal, do you have any updates? 

Looking forward to your reply.

**Comment by ghost** [comment]
Hello @Saumyadip-Pramanik 

The status of the ticket changed to "Closed" due to the absence of a reply from you.

If this ticket is still relevant for you - re-open it and provide me with the requested information.
