### ISSUE TITLE
couldn't create dialog in ios

### ISSUE THREAD

**Issue by bobananto24** [QuickBlox/quickblox-react-native-sdk#36]
I was trying to create a dialog using quickblox react-native-sdk. In ANDROID it worked perfectly fine, but in IOS(simulator) it is showing Error: Request failed: client error (422)

this is my code:
QB.chat
      .createDialog({
        type: QB.chat.DIALOG_TYPE.CHAT,
        occupantsIds: [127929951],
      })
      .then(function (dialog) {
        console.log(dialog);
        
      })
      .catch(function (e) {
        console.log(e);  
      });

**Comment by arnabadhikari2009** [comment]
The same issue arises on my end ... Did anyone find any solution?

**Comment by ghost** [comment]
Hello Boban and Arnabad,

This is Nikolay from QuickBlox support.

Thank you for reporting the issue.

We will release a fix in the near future.

For now, to avoid this issue you can try not to pass the type when creating a dialog. The SDK should detect the dialog type based on the data provided.

You can follow our React Native developer here: [oleksandr-shvetsov-qb · GitHub](https://github.com/oleksandr-shvetsov-qb)
