### ISSUE TITLE
User image not available in QB.getDialogs method.

### ISSUE THREAD

**Issue by Saumyadip-Pramanik** [QuickBlox/quickblox-react-native-sdk#4]
React-Native: 0.61.4
QB: 0.4.11-beta

Unable to show user images in the dialog list screen.

Logs:
{"dialogs": [{"createdAt": "2020-01-06T15:14:08Z", "id": "5e134ec0a28f9a14cc9fe3ba", "isJoined": true, "lastMessage": "Hay", "lastMessageDateSent": 1578499188000, "lastMessageUserId": 102069823, "name": "Saumyadip Pramanik", "occupantsIds": [Array], "type": 3, "unreadMessagesCount": 0, "updatedAt": "2020-01-08T15:59:48Z", "userId": 102069823}], "limit": 30, "skip": 0, "total": 1}

We are sharing the 'website' => $imageUrl while creating the user account from PHP.

**Comment by ghost** [comment]
Hello @Saumyadip-Pramanik 

Please provide reproducing steps for this issue.

Have you tried to reproduce the same with our official sample?

https://github.com/QuickBlox/quickblox-react-native-samples/tree/master/chat-sample

**Comment by ghost** [comment]
Hello @Saumyadip-Pramanik 

The status of the ticket changed to "Closed" due to the absence of a reply from you.

If this ticket is still relevant for you - re-open it and provide me with the requested information.

**Comment by ReactAndroidDev** [comment]
Any update on this issue.
