### ISSUE TITLE
How to change views in full screen like whatsapp? i want to create like them

### ISSUE THREAD

**Issue by mindrootstech** [QuickBlox/quickblox-react-native-sdk#40]

**Comment by ghost** [comment]
Hello @mindrootstech ,

This is Nikolay from QuickBlox support.

Unfortunately, the query is not clear enough for us. 
Please provide us with more detailed information about the workflow you want to achieve.

You may also attach a video or screenshots.

Thank you in advance.

**Comment by ayushjain1796** [comment]
hi @QB-nikolay-zolotarov , in my experience when you are on 1-1 call with someone quickblox uses 50-50 screen ration for both the persons on the call, and if I'm not wrong what @mindrootstech want's is something like that the remote peer takes up the 100% of the screen and the local peer takes the same box in bottom left or right corner

**Comment by ghost** [comment]
@ayushjain1796 Hello,

Thank you for your reply.

Please let me know if you observe the same behavior with the latest version of our SDK:
[https://github.com/QuickBlox/quickblox-react-native-sdk/releases/tag/0.5.14-beta](https://github.com/QuickBlox/quickblox-react-native-sdk/releases/tag/0.5.14-beta)
