### ISSUE TITLE
How to remove 'The call service is ready' notification in android?

### ISSUE THREAD

**Issue by rahulcs1989** [QuickBlox/quickblox-react-native-sdk#41]
In android I am getting notification like 'The call service is ready Quickblox'. I am not able to remove it. Appreciate any help :)

**Comment by ghost** [comment]
Hello Rahul @rahulcs1989 ,

This is Nikolay from QuickBlox support.

According to [Google requirements](https://developer.android.com/guide/components/foreground-services), each foreground service must show a [status bar notification](https://developer.android.com/guide/topics/ui/notifiers/notifications). To hide the notification, you need to stop the service.

Please refer to the corresponding documentation:
React Native SDK - [Video Calling | React Native SDK | QuickBlox](https://docs.quickblox.com/docs/react-native-video-calling#release-resource)

Also, you can change the text of the notification in the following file on GitHub: /android/src/main/res/values/strings.xml.

Additionally, you can change the logo by replacing the files ic_call_service_large.png and ic_call_service_small.png in the following folder on GitHub:
android/src/main/res/mipmap/

**Comment by ashwanihundwani** [comment]
@QB-nikolay-zolotarov - While in audio call, I am also getting the same. Firstly, why are we using a foreground service in Quickblox Android SDK? Does WhatsApp or any other audio/video apps are also required to show some status bar notification in such cases?

**Comment by ashwanihundwani** [comment]
Also, If i stop the service, will I receive the events like incoming calls? Is it possible to restrict the notification to appear only when call related events are happening like from "start of the call" to "end of the call"

**Comment by ghost** [comment]
Hi @ashwanihundwani,
Using foreground service is Android requirement for services of certain categories, you can read more at [Android developer](https://developer.android.com/guide/components/foreground-services) portal.
At the moment if you want to enable calling functionality in QuickBlox React Native SDK - **webrtc** module should be initialized. This ensures that SDK is able to work with call in background / locked screen, send events about calls (incoming call, call has ended etc.).
Stay tuned to know when new version will be released and this will be changed - service notification will appear like from "start of the call" to "end of the call".

**Comment by ashwanihundwani** [comment]
Thanks  @oleksandr-shvetsov-qb  So by this you mean your team is working to restrict notification to be shown between "start of the call" to "end of the call"? Just seeking confirmation from you.

Also, Is there a plan to expose public setters for title, message and app icon to be shown in status bar notification? As we are getting title "The call service is ready" and text at the bottom "Quickblox". We cannot show "Quickblox" in our app.  As the solution provided by Nikolay above does not seems to be ideal. I this we should not change library code and assets. Let me know if this makes sense for you.

**Comment by ghost** [comment]
@ashwanihundwani 
Yes, refactoring the call service is in our roadmap.
In order to change foreground service notification text you should set your values into `android/src/main/res/values/strings.xml`:
```xml
<resources>
    //Call
    <string name="notification_title_call">Calling…</string>
    <string name="notification_text_call">Touch takes you back to the call %1$s</string>
    //Incoming
    <string name="notification_title_incoming">You have incoming call</string>
    <string name="notification_text_incoming">Incoming call from %1$s</string>
    //Outgoing
    <string name="notification_title_outgoing">You have outgoing call</string>
    <string name="notification_text_outgoing">Outgoing call to %1$s</string>
    <!--Commons-->
    <string name="app_name">Sample React Native WebRTC</string>
    <string name="call_time_format">%%0%dd</string>
    <!--Call Service-->
    <string name="call_service_notification_title">The call service is ready</string>
    <string name="call_service_notification_text">Quickblox</string>
</resources>
```
In order to change foreground service icons put your icons named `ic_call_service_large.png` and `ic_call_service_small.png` into `android/src/main/res/mipmap/` of your app.

**Comment by roldanunne** [comment]
You can create `android/src/main/res/values/strings.xml` and add the ff string value
    <string name="webrtc_call_service_notification_text"></string>
    <string name="webrtc_call_service_notification_title">MyApps service is ready</string>
