### ISSUE TITLE
could not build module 'QuickbloxWebRTC'

### ISSUE THREAD

**Issue by imransiddiqui511** [QuickBlox/quickblox-react-native-sdk#45]
fatal error: could not build module 'QuickbloxWebRTC'
#import <QuickbloxWebRTC/QuickbloxWebRTC.h>
 ~~~~~~~^
2 errors generated.

**Comment by ghost** [comment]
@imransiddiqui511 Hello,

This is Nikolay from QuickBlox support.

Please make sure that you followed our documentation:
https://docs.quickblox.com/docs/react-native-quick-start
https://docs.quickblox.com/docs/react-native-setup

Also, please try using our samples:
https://github.com/QuickBlox/quickblox-react-native-samples/tree/master/webrtc-sample
