### ISSUE TITLE
Error: The call service is not connected

### ISSUE THREAD

**Issue by threeng0227** [QuickBlox/quickblox-react-native-sdk#46]
Error: The call service is not connected when making a call on Android.

**Comment by ghost** [comment]
Hello @nhoxx 

This is Nikolay from QuickBlox support.

According to the error message, WebRTC was not initialized.

Please initialize WebRTC according to our documentation:
https://docs.quickblox.com/docs/react-native-video-calling#initialize-webrtc

Also, you may use our video calling sample where this functionality is implemented correctly:
https://github.com/QuickBlox/quickblox-react-native-samples/tree/master/webrtc-sample

If the sample works as expected from your side, you can take it as an example for further integration of video calls into your applications/projects.
