### ISSUE TITLE
How to delete a message from chat?

### ISSUE THREAD

**Issue by joytomchin** [QuickBlox/quickblox-react-native-sdk#47]
How to delete a message from chat?

**Comment by ghost** [comment]
@joytomchin Unfortunately, the functionality of deleting messages is not described in our React Native SDK.

According to our developers, It is planned for development. However, there is no ETA.

You may refer to the iOS and Android documentation to write it natively:
https://docs.quickblox.com/docs/android-chat-messaging#delete-message
https://docs.quickblox.com/docs/ios-chat-messaging#delete-message
