### ISSUE TITLE
attempt to invoke virtual method 'boolean java.lang.string.equals

### ISSUE THREAD

**Issue by joytomchin** [QuickBlox/quickblox-react-native-sdk#49]
attempt to invoke virtual method 'boolean java.lang.string.equals

**Comment by ghost** [comment]
@joytomchin Hello,

This is Nikolay from QuickBlox support.

Please provide us with more detailed information about the issue and step-by-step instructions on how to reproduce it on our end.

Also, please provide full logs. You can find out how to gather logs here: [Gathering logs guides - QuickBlox Help Center](https://help.quickblox.com/article/368-how-can-i-enable-quickblox-logs)

**Comment by joytomchin** [comment]
<img width="406" alt="Screenshot 2022-03-03 at 4 08 39 PM" src="https://user-images.githubusercontent.com/79104219/156548493-0120b0eb-3def-402d-b7d9-4045faf3e9fa.png">

**Comment by ghost** [comment]
To investigate the issue, I need more detailed information like full logs, a description, steps to reproduce. Please provide me with that so I can help you.
