### ISSUE TITLE
Push Notification is not delivered.

### ISSUE THREAD

**Issue by Saumyadip-Pramanik** [QuickBlox/quickblox-react-native-sdk#5]
React-Native: 0.61.4
QB: 0.4.11-beta

Hi QB Team,

I have configured the push notification setting in my QB panel but, the notification is not coming in the device. I have also checked the Server Key and SSL configuration in my end, the notification is being delivered from Firebase console.

I have also informed this to QB-vladyslav-vyshniak in our one to one communication. Please review.

**Comment by ghost** [comment]
Hello @Saumyadip-Pramanik 

Thank you for contacting QuickBlox support.

Please, be notified, that we have discussed only the ticket #146282 / https://github.com/QuickBlox/quickblox-react-native-sdk/issues/3

Could you provide me with the answers to the following questions.
1. Does APNS work as expected?
2. Have you tried to send a notification via your QuickBlox admin panel? Did it work? 

Looking forward to your reply.

**Comment by mukeshcliffex** [comment]
Hi, I am facing same issue.
In queue, status of message is sent but it is not delivered on phone

**Comment by samcomkishan** [comment]
@QB-vladyslav-vyshniak 

Hello

I tried sending notification from quickblox admin panel as well but it didn't work, it just says, notification is sent but 0 delivered.

When I send the notification it gives below response
`{
  "active": true,
  "id": 987654321,
  "payload": {
    "data.message": "JTdCJTIydHlwZSUyMiUzQSUyMmNhbGwlMjIlMkMlMjJzZXNzaW9uJTIyJTNBJTdCJTIyb3Bwb25lbnRzSWRzJTIyJTNBJTVCMTI3NTA0MTIyJTVEJTJDJTIyaW5pdGlhdG9ySWQlMjIlM0ExMjU0ODk3OTglMkMlMjJzdGF0ZSUyMiUzQTAlMkMlMjJ0eXBlJTIyJTNBMSUyQyUyMmlkJTIyJTNBJTIyZjIzZGNiMTItOTg0OC00MjM4LTkyZDgtY2UyYzdmNjFmMmU5JTIyJTdEJTdE"
  },
  "pushType": 3,
  "senderId": 123456789
}
`

Looking forward to your response

**Comment by bhattjaldhi** [comment]
@QB-vladyslav-vyshniak 

Hello

1. I tried calling notification from Quickblox admin panel as well, it says notification has been "sent" but 0 delivered
Note that in react native app, notification is also subscribed, also firebase push notification from firebase console works well.

2. When I send notification from react-native I get below response

`{
  "active": true,
  "id": 37321597,
  "payload": {
    "data.message": "JTdCJTIydHlwZSUyMiUzQSUyMmNhbGwlMjIlMkMlMjJzZXNzaW9uJTIyJTNBJTdCJTIyb3Bwb25lbnRzSWRzJTIyJTNBJTVCMTI3NTA0MTIyJTVEJTJDJTIyaW5pdGlhdG9ySWQlMjIlM0ExMjU0ODk3OTglMkMlMjJzdGF0ZSUyMiUzQTAlMkMlMjJ0eXBlJTIyJTNBMSUyQyUyMmlkJTIyJTNBJTIyZjIzZGNiMTItOTg0OC00MjM4LTkyZDgtY2UyYzdmNjFmMmU5JTIyJTdEJTdE"
  },
  "pushType": 3,
  "senderId": 125489798
}
`

Platform: Android

Looking forward to your reply
