### ISSUE TITLE
Getting different reponses in different platforms

### ISSUE THREAD

**Issue by bobananto24** [QuickBlox/quickblox-react-native-sdk#50]
Not getting "updated_at" value in success response of QB.chat.getDialogMessages() in IOS 
**Response in Android**: properties: {all_read: 'true', updated_at: '2022-03-14T11:36:22Z', customParam1: 'null', read: '1'}
**Response in IOS**: properties: {customParam1: 'null', read: 1, all_read: true}
Thank in advance

**Comment by ghost** [comment]
@bobananto24 Hello,

This is Nikolay from QuickBlox support.

We are aware of this inconsistency. Our developers are working on it. However, it will take more time.

Please check this page for updates:
https://help.quickblox.com/article/250-the-latest-version-of-quickblox-react-native-sdk
