### ISSUE TITLE
getting error in creating dialog

### ISSUE THREAD

**Issue by ubaid-wp** [QuickBlox/quickblox-react-native-sdk#51]
I am trying to create a dialog  but it is showing Error :  [Error: "base" Forbidden. Need user.
]
  const createDialogParams = {
        type: QB.chat.DIALOG_TYPE.CHAT,
        occupantsIds: [134752411]
    }

    QB.chat
        .createDialog(createDialogParams)
        .then(function (dialog) {
            console.log('dialog======', dialog)
        })
        .catch(function (e) {
            console.log('e=========', e)
        })

**Comment by ghost** [comment]
@ubaid-wp Hello, this is Nikolay from QuickBlox support. You need to log in before creating a dialog:
https://docs.quickblox.com/docs/react-native-authentication#log-in-user
