### ISSUE TITLE
new NativeEventEmitter() warning

### ISSUE THREAD

**Issue by jzafar** [QuickBlox/quickblox-react-native-sdk#52]
I am using NativeEventEmiter to receive new message But i am getting waring on Android 
`new NativeEventEmitter()` was called with a non-null argument without the required `removeListeners` method. 
Here is my code

useEffect(() => {
    var emitter = new NativeEventEmitter(QB.chat);
    emitter.addListener(
      QB.chat.EVENT_TYPE.RECEIVED_NEW_MESSAGE,
      receivedNewMessage,
    );
    return () => {
      emitter.removeAllListeners(QB.chat);
    };
  }, []);

**Comment by ghost** [comment]
Hello @jzafar, this is Nikolay from QuickBlox support.
To investigate the issue further, please provide the following points:
1. The QuickBlox React Native SDK version.
2. Is this issue intermittent or permanent?
3. Please provide step-by-step instructions on how to reproduce the issue on our end.
4. Did you get this issue in your code or on samples?
5. Please try reproducing the issue on our samples and let me know:
https://github.com/QuickBlox/quickblox-react-native-samples/tree/master/chat-sample
6. Please provide me with full logs from the application start till the request and "wrong" response (error).
You can find out how to gather logs here: [Gathering logs guides - QuickBlox Help Center](https://help.quickblox.com/article/368-how-can-i-enable-quickblox-logs)
7. Devices in use (e.g. Redmi 8).
8. React Native version.
9. Information from react-native info.
10. Information from npm list.

**Comment by jzafar** [comment]
Hi Nikolay here is more information 
1. "quickblox-react-native-sdk": "^0.6.0-beta"
2. It's permanent issue
3. I have added this listener in my custom class and i have written code above what i am doing. when app load this class i got this warning.
4. In my own code
5.  I can't build chat-sample app with this version "quickblox-react-native-sdk": "^0.5.14-beta", But when i try with "quickblox-react-native-sdk": "^0.6.0-beta", it gives > Task :app:processDebugGoogleServices FAILED 
6. there is no way defined to get logs for react native sdk
7. I am running app on google pixel 4 android 11
8. "react-native": "0.68.1",
9.
System:
    OS: macOS 12.3.1
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 58.08 MB / 32.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.15.0 - /usr/local/bin/node
    Yarn: 1.22.18 - /usr/local/bin/yarn
    npm: 8.5.5 - /usr/local/bin/npm
    Watchman: 2022.03.21.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /Users/zafar/.rvm/gems/ruby-3.0.0/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.4, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.2 AI-212.5712.43.2112.8512546
    Xcode: 13.3.1/13E500a - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.2 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.68.1 => 0.68.1 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
10.
├── @babel/core@7.17.10
├── @babel/runtime@7.17.9
├── @baronha/react-native-multiple-image-picker@0.4.10
├── @invertase/react-native-apple-authentication@2.1.5
├── @jimp/bmp@0.16.1 extraneous
├── @jimp/core@0.16.1 extraneous
├── @jimp/custom@0.16.1 extraneous
├── @jimp/gif@0.16.1 extraneous
├── @jimp/jpeg@0.16.1 extraneous
├── @jimp/plugin-blit@0.16.1 extraneous
├── @jimp/plugin-blur@0.16.1 extraneous
├── @jimp/plugin-circle@0.16.1 extraneous
├── @jimp/plugin-color@0.16.1 extraneous
├── @jimp/plugin-contain@0.16.1 extraneous
├── @jimp/plugin-cover@0.16.1 extraneous
├── @jimp/plugin-crop@0.16.1 extraneous
├── @jimp/plugin-displace@0.16.1 extraneous
├── @jimp/plugin-dither@0.16.1 extraneous
├── @jimp/plugin-fisheye@0.16.1 extraneous
├── @jimp/plugin-flip@0.16.1 extraneous
├── @jimp/plugin-gaussian@0.16.1 extraneous
├── @jimp/plugin-invert@0.16.1 extraneous
├── @jimp/plugin-mask@0.16.1 extraneous
├── @jimp/plugin-normalize@0.16.1 extraneous
├── @jimp/plugin-print@0.16.1 extraneous
├── @jimp/plugin-resize@0.16.1 extraneous
├── @jimp/plugin-rotate@0.16.1 extraneous
├── @jimp/plugin-scale@0.16.1 extraneous
├── @jimp/plugin-shadow@0.16.1 extraneous
├── @jimp/plugin-threshold@0.16.1 extraneous
├── @jimp/plugins@0.16.1 extraneous
├── @jimp/png@0.16.1 extraneous
├── @jimp/tiff@0.16.1 extraneous
├── @jimp/types@0.16.1 extraneous
├── @jimp/utils@0.16.1 extraneous
├── @react-native-async-storage/async-storage@1.17.6
├── @react-native-community/eslint-config@2.0.0
├── @react-native-community/geolocation@2.1.0
├── @react-native-firebase/app@14.9.1
├── @react-native-google-signin/google-signin@7.2.2
├── @react-navigation/bottom-tabs@6.3.1
├── @react-navigation/material-top-tabs@6.2.1
├── @react-navigation/native-stack@6.6.2
├── @react-navigation/native@6.0.10
├── @stripe/stripe-react-native@0.12.0
├── any-base@1.1.0 extraneous
├── axios@0.27.2
├── babel-jest@26.6.3
├── bmp-js@0.1.0 extraneous
├── buffer-equal@0.0.1 extraneous
├── dom-walk@0.1.2 extraneous
├── eslint@7.32.0
├── exif-parser@0.1.12 extraneous
├── file-type@9.0.0 extraneous
├── gifwrap@0.9.4 extraneous
├── global@4.4.0 extraneous
├── image-q@4.0.0 extraneous
├── is-function@1.0.2 extraneous
├── jest@26.6.3
├── jimp@0.16.1 extraneous
├── jpeg-js@0.4.2 extraneous
├── load-bmfont@1.4.1 extraneous
├── metro-react-native-babel-preset@0.67.0
├── min-document@2.19.0 extraneous
├── moment@2.29.3
├── omggif@1.0.10 extraneous
├── pako@1.0.11 extraneous
├── parse-bmfont-ascii@1.0.6 extraneous
├── parse-bmfont-binary@1.0.6 extraneous
├── parse-bmfont-xml@1.1.4 extraneous
├── parse-headers@2.0.5 extraneous
├── phin@2.9.3 extraneous
├── pixelmatch@4.0.2 extraneous
├── pngjs@3.4.0 extraneous
├── process@0.11.10 extraneous
├── quickblox-react-native-sdk@0.6.0-beta
├── react-hook-form@7.31.1
├── react-native-bootsplash@4.1.5 extraneous
├── react-native-date-picker@4.2.2
├── react-native-fbsdk@3.0.0
├── react-native-geocoding@0.5.0
├── react-native-geolocation-service@5.3.0-beta.4
├── react-native-google-places-autocomplete@2.4.1
├── react-native-in-app-review@4.1.1
├── react-native-keyboard-aware-scroll-view@0.9.5
├── react-native-keyboard-aware-view@0.0.14
├── react-native-linear-gradient@2.5.6
├── react-native-maps@0.31.1
├── react-native-modal@13.0.1
├── react-native-modalbox@2.0.2
├── react-native-pager-view@5.4.24
├── react-native-permissions@3.3.1
├── react-native-ratings@8.1.0
├── react-native-safe-area-context@4.2.5
├── react-native-screens@3.13.1
├── react-native-tab-view@3.1.1
├── react-native-toast-message@2.1.5
├── react-native-webview@11.22.0
├── react-native@0.68.1
├── react-test-renderer@17.0.2
├── react@17.0.2
├── timm@1.7.1 extraneous
├── tinycolor2@1.4.2 extraneous
├── utif@2.0.1 extraneous
├── xhr@2.6.0 extraneous
└── xml-parse-from-string@1.0.1 extraneous

**Comment by foobarsik** [comment]
Had the same issue. I think it's due latest react-native versions. We use 0.69.7 react-native version in our project. This worked for me:

```
      const emitter = new NativeEventEmitter();
      emitter.addListener(QB.chat.EVENT_TYPE.RECEIVED_NEW_MESSAGE, event => {
         const {type, payload} = event;
         console.log(type);
         console.log(payload);
      });
```
