### ISSUE TITLE
how to handel  QB.chat.sendIsTyping properly to show user sender is typing  

### ISSUE THREAD

**Issue by ardhendu12345** [QuickBlox/quickblox-react-native-sdk#53]
const isTypingParams = { dialogId: dialogId };

QB.chat
  .sendIsTyping(isTypingParams)
  .then(function () {
    /* sent successfully */
    console.log("user is typing");
  })
  .catch(function (e) {
    /* handle error */
    console.log("user is typing error", e);
  });
Please help ...new to react-native

**Comment by ghost** [comment]
@ardhendu12345 Hello, this is Nikolay from QuickBlox support. 
At this point I can suggest checking our sample where this functionality is implemented correctly:
https://github.com/QuickBlox/quickblox-react-native-samples/tree/master/chat-sample
