### ISSUE TITLE
Getting error on QB.chat.sendMessage() on android but works on ios

### ISSUE THREAD

**Issue by MCSKTLZ** [QuickBlox/quickblox-react-native-sdk#60]
I have this code 

` const sendMessage = useCallback(async (dialogId: string, body: string) => {
    try {
      const message = {
        dialogId,
        body,
        saveToHistory: true,
      };
      const result = await QB.auth.getSession();

      console.log({ result });

      await QB.chat.sendMessage(message);
      console.log('Message sent');
    } catch (errorMessage) {
      console.log({ errorMessage });
    }
  }, []); `

It works on ios but i get this error on android : 
"Error: Attempt to invoke virtual method 'int com.quickblox.auth.session.QBSessionParameters.getUserId()' on a null object reference]}"

I got the session everything else work, I can receive messages, get my dialogs, I just can't send messages on android.

Anyone have a solution ?

**Comment by kirillTolmachev** [comment]
@MCSKTLZ 
Hello. 
Could you please provide versions of Flutter Quickblox SDK, Android OS Version, and Dialog type (public, private, group).

**Comment by MCSKTLZ** [comment]
@kirillTolmachev 
Hi,
I'm not using flutter, I'm using React native sdk.

React native version: "quickblox-react-native-sdk": "^0.9.1"
Android OS version: 12 on android studio emulator
And I tried private and group dialog, either get the same error but I didn't tried public.

As I said above everything else work and I try to get the session just before sending the message to test and I got it

**Comment by kirillTolmachev** [comment]
@MCSKTLZ 
Does the issue reproduce on a real device?

**Comment by MCSKTLZ** [comment]
@kirillTolmachev 
Same error on real device android version 13

**Comment by kirillTolmachev** [comment]
@MCSKTLZ 
I have added a fix. 
In a new version of ReactNative Quickblox SDK, the issue will be fixed.

**Comment by MCSKTLZ** [comment]
@kirillTolmachev 
Thanks for the fast support.
