### ISSUE TITLE
The session never get cleared so I can't start a new one with the session token 

### ISSUE THREAD

**Issue by MCSKTLZ** [QuickBlox/quickblox-react-native-sdk#62]
Hello, 

When I try to reconnect after some time, I send a new session token from my API 
and try to start a new session but I get this error : [Error: base Required session does not exist]

I found that I'm still on an expirated session even when I do QB.auth.logout and so the QB.startSessionWithToken get the error and can't connect to a new session.

Here is the code : 
`const startSessionWithToken = useCallback(async () => {
    try {
      await QB.chat.disconnect();
      await QB.auth.logout();

      await QB.settings.init(appSettings);

      const result3 = await QB.auth.getSession();

      console.log({ result3 });

      console.log(sessionToken);

      const result2 = await QB.auth.startSessionWithToken(sessionToken);
      console.log({ result2 });

    } catch (error) {
      console.log({ error });
    }
  }, []);`

The getSession method return an expired session !

I found in the javascript sdk that there is a QB.destroySession method but not in the React native sdk.

are there any solutions ?

**Comment by IlliaChemolosov** [comment]
Hello @MCSKTLZ 
This is Illia from QuickBlox.

The error: [Error: base Required session does not exist] is a [Server API](https://docs.quickblox.com/reference/get-session) Error that returned when called the `QB.auth.startSessionWithToken()` method with wrong token. Please, check the qb session token that you receive from your backend.

More info: https://docs.quickblox.com/docs/react-native-setup#initialize-quickblox-sdk-without-authorization-key-and-secret

**Comment by MCSKTLZ** [comment]
Hello @IlliaChemolosov ,

The token is good I tested with postman and it is valid I can connect the user with it in postman.

The problem here is when I let the app killed without touching for some time when I want to reconnect the app as already an expired session who won't clear even if I call QB.auth.logout and then I can't connect with the new token I send from my API (btw I use the same method every time to create a user session token so it cannot be that because otherwise it will never work).

I have to deinstall the app and reinstall it to clear the session and make it work again.

The weird thing is that when I'm connected and using the app, refreshing the token works perfectly.

**Comment by IlliaChemolosov** [comment]
@MCSKTLZ,

What version of RN SDK and what platform (iOS/Android) are you running the problem on?

**Comment by MCSKTLZ** [comment]
@IlliaChemolosov,

React native sdk: 0.9.2
Platform: both iOS and android

**Comment by IlliaChemolosov** [comment]
@MCSKTLZ ,

We need some time to reproduce the issue. You can speed up the process by sending us a log file, a sample code etc. You can speed up the process by sending us a log file, a sample code etc.

**Comment by MCSKTLZ** [comment]
Hello @IlliaChemolosov , 

I opened my app this morning with this code :

`const startSessionWithToken = useCallback(async () => {
    try {
      await QB.auth.logout();

      await QB.settings.init(appSettings);

      const result3 = await QB.auth.getSession();

      console.log({ result3 });

      // await QB.settings.enableCarbons();
      console.log(sessionToken);

      const result2 = await QB.auth.startSessionWithToken(sessionToken);
      console.log({ result2 });

      // await QB.settings.enableAutoReconnect({ enable: true });
    } catch (error) {
      console.log({ error });
    }
  }, []);`

and it is called at the begin of the app. 
Everything worked fine yesterday until 21h then I wasn't able to connect to QuickBlox.

I get this from my console.log : 

{"result3": {"applicationId": 98...., "expirationDate": "2023-01-11T20:58:07+0000", "token": "eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3NfdHlwZSI6InVzZXJfYWNjZXNzIiwiYXBwbGljYXRpb25faWQiOjk4O..........fn_jY64L1LSw3T1t066YHXK15Y9qk_KvfzkRnzjlQu4FIrF_8EItY9PZIxqtlSp5Q", "userId": 13639.....}}

sessionToken : "eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3NfdHlwZSI6InVzZXJfYWNjZXNzIiwiYXBwbGljYXRpb25faWQiOjk4O............8lm7d4w1wEplWcBcydLw5K3LKZT80TgaCh3jit8vkn4kkdeoVtKArnNp6w"

 {"error": [Error: base Required session does not exist]}

So I got the new token who is valid on Postman but the session is locked to an older and expired session.

**Comment by IlliaChemolosov** [comment]
Hello @MCSKTLZ ,
We were unable to reproduce the issue you described above on our end. 

Please try to reproduce the issue on our clear “Set existing session” new sample.
You can find the sample here: https://github.com/QuickBlox/quickblox-react-native-samples/tree/set-existing-session-sample
If the issue is reproduced, please provide us with full logs as attachment in .txt format.

**Comment by MCSKTLZ** [comment]
Hello @IlliaChemolosov 
This issue persist !

After some time if the the session is expired I can't even logout from this session so I can't set a new session with my new user session token. I just need some way to destroy the session if the app is stuck on the expired one.

**Comment by aurelbe** [comment]
Same problem here

**Comment by IlliaChemolosov** [comment]
Hello @MCSKTLZ , @orel91 
Please, reproduce the issue on our clear [Set existing session](https://github.com/QuickBlox/quickblox-react-native-samples/tree/set-existing-session-sample) sample and provide us with full logs as attachment in .txt format.

**Comment by MCSKTLZ** [comment]
Hello @IlliaChemolosov,

I reproduced this issue with your sample here is the logs attached.

**Comment by IlliaChemolosov** [comment]
Hello @MCSKTLZ,
Thank you for providing the log file. We have reproduced the problem and are working on a solution.

**Comment by IlliaChemolosov** [comment]
Hello @MCSKTLZ ,
The new version of the SDK(0.9.4) with a resolution to the issue has been released. Thank you for your support and assistance.
