### ISSUE TITLE
Does the SDK work with Expo?

### ISSUE THREAD

**Issue by Theeeus** [QuickBlox/quickblox-react-native-sdk#63]
I was wondering if the SDK works with Expo at all and if so if there's any documentation specific for installing the SDK in an Expo project

**Comment by spaceod** [comment]
Hey @Theeeus, instead of Quickblox, I would suggest that you use either Sendbird (https://sendbird.com/) or Stream (https://getstream.io/chat/). Based on our experience with the project, we've encountered a lot of issues with Quickblox's SDK.

**Comment by Theeeus** [comment]
Hey @spaceod thanks for the tip. So the issues you had with Quickblox SDK were while using Expo?

**Comment by IlliaChemolosov** [comment]
@Theeeus Hello!
It's Illia from QuickBlox.

QuickBlocks SDK contains custom native code. So I recommend you to research Expo documentation specific for ["Add custom native code"](https://docs.expo.dev/workflow/customizing/) where they describe how to make use of third-party libraries with custom native code.
