### ISSUE TITLE
is there a way to make call when app is closed? 

### ISSUE THREAD

**Issue by russelRajitha** [QuickBlox/quickblox-react-native-sdk#7]
is there a way to make call when app is closed? currently everything works fine when app is minimized. but when app is in closed status incoming calls are not appears.

**Comment by HarshitPKing** [comment]
I am facing the same issue in the latest SDK.

**Comment by Trosdan** [comment]
Im using the PushNotification to init que webrtc module.

**Comment by jpgarcia99** [comment]
Would you know if there is sample code on how to do that?  Thanks!

**Comment by Trosdan** [comment]
When the user A start the call he send a notification using the QuickBlox PushNotification

```javascript
const event = {
  notificationType: QB.events.NOTIFICATION_TYPE.PUSH,
  payload: {
    ios_voip: 1, for iOS voip push
    message: 'Your push notification message',
    VOIPCall: 1, for android voip push
  },
  recipientsIds: session.opponentsIds, // send push to call opponents
  senderId: session.initiatorId, // in case you're call initiator
  type: QB.events.NOTIFICATION_EVENT_TYPE.ONE_SHOT,
}

QB.events
  .create(event)
  .then(function (data) { /* notification event(s) created successfully */ })
  .catch(function (e) { /* handle error */ })
```
When user B receives a notification and his application is closed or Background is tested if the notification is a VOIP push, if true, the webrtc module will be initialized

```javascript
messaging().setBackgroundMessageHandler(async remoteMessage => {
  if (remoteMessage.data.VOIPCall) {
    PushNotification.localNotification({
      title: 'My App - CALL',
      message: remoteMessage.data.message,
      largeIcon: 'icon',
      smallIcon: 'icon',
    });
    yield put(qbConnectChatRequest());
  } else {
    PushNotification.localNotification({
      title: 'My App - CHAT',
      message: remoteMessage.data.message,
      group: 'batepapo',
      largeIcon: 'icon',
      smallIcon: 'icon',
      vibrate: true,
      playSound: false,
      soundName: 'default',
    });
  }
}
```

I'm using the Firebase Cloud Message to get the FCM token and run the script in background and QuickBlox to persist the FCM token

**Comment by ghost** [comment]
@jpgarcia99 @HarshitPKing @russelRajitha Hello,

This is Nikolay from QuickBlox support.

The question is related to the implementation of push notifications.

Please refer to our documentation:
[https://docs.quickblox.com/docs/react-native-push-notifications](https://docs.quickblox.com/docs/react-native-push-notifications)

Also, you may use this guide to the configuring push notifications:
[https://help.quickblox.com/article/268-configuration-of-chat-and-video-push-notifications](https://help.quickblox.com/article/268-configuration-of-chat-and-video-push-notifications)

Please keep in mind that managing and configuring push notifications in the background mode or killed state is not a part of QuickBlox SDK's and the implementation is up to the client side.
