### ISSUE TITLE
Unable to add photo to private chat

### ISSUE THREAD

**Issue by maharjanaman** [QuickBlox/quickblox-react-native-sdk#70]
While creating dialog, when I passed `photo` property with image url to create dialog params, the `photo` property is not being updated on quickblox dashboard.

**Comment by IlliaChemolosov** [comment]
@maharjanaman 
Please note that the photo field is not supported in private chat. For more details, refer to our [documentation](https://docs.quickblox.com/docs/react-native-chat-dialogs#create-dialog). In such cases, we recommend utilizing the opponent's avatar. Additionally, you have the option to pass your own unique field using custom data (ensure not to use fields already employed in the dialog object).

**Comment by VladimirNybozhinsky** [comment]
Hello! @maharjanaman 
This is Vladimir from QuickBlox.

According to the [documentation](https://docs.quickblox.com/reference/dialog-model),
“Group chat photo. It makes sense if type=1 (PUBLIC_GROUP) or type=2 (GROUP).
Can contain a link to a file in the Content module, the Custom Objects module, or simply a web link."

For private chat (1-1), use your opponent’s [photo](https://docs.quickblox.com/docs/react-native-users#set-user-avatar).

Best regards, Vladimir

**Comment by maharjanaman** [comment]
Thanks for the response. I'll close the issue for now.
