### ISSUE TITLE
FCM subscription is being created for development environment only

### ISSUE THREAD

**Issue by maharjanaman** [QuickBlox/quickblox-react-native-sdk#73]
While creating a push notification subscription for the Android platform, the subscription Is created under the development environment only. I see there is an option to set env in the native Android SDK example but how to set env using React Native SDK?

**Comment by IlliaChemolosov** [comment]
Hello @maharjanaman !

We advise against installing the environment using native code, as it may impact the proper functioning of the features. Instead, we recommend upgrading to the latest version of SDK 0.9.7, which incorporates the functionality to automatically configure the environment based on your build type. To ensure the Live notifications work seamlessly, please compile and run the release build. 

Thank you.

**Comment by maharjanaman** [comment]
@IlliaChemolosov Thank you for your time. Is there a manual way to set the environment? Right now, the env is set to production for debug build also.

**Comment by kirillTolmachev** [comment]
Hello @maharjanaman 
The environment will be set according to build type. 
The code to setup environment type looks like below:

```
qbSubscription.setEnvironment(QBEnvironment.PRODUCTION);
if (BuildConfig.DEBUG) {
       qbSubscription.setEnvironment(QBEnvironment.DEVELOPMENT);
}
```

This means if you set any type of build except **DEBUG** then the environment will be **PRODUCTION**. When you set the environment to **DEBUG** then the environment will be **DEVELOPMENT**.

There is no any another ways to setup environment manualy.
