### ISSUE TITLE
Reinitialize QB with different credentials after app start

### ISSUE THREAD

**Issue by maharjanaman** [QuickBlox/quickblox-react-native-sdk#77]
Is there a way to reinitialize QB with different credentials after the app has started? The scenario is the app that has multiple accounts and each account is associated with a different QB project. So, when the user switches the account, QB needs to be initialized with the credentials of that account.

**Comment by IlliaChemolosov** [comment]
Hello @maharjanaman !

We haven't conducted tests related to the implementation of such functionality, but theoretically, it can be done by performing the following steps before changing the account:

1. Disconnect from the chat.
2. Log out.
3. Initialize new credentials (for Android, restarting the application with code in the navigational part may be necessary before initialization).
4. Log in.
5. Connect to the chat.

**Comment by maharjanaman** [comment]
I'll close this here in favor of the support ticket.
